"""fix user fields

Revision ID: 9056e44eae8a
Revises: 5de239af28aa
Create Date: 2026-08-15 09:17:47.933644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9056e44eae8a'
down_revision: Union[str, Sequence[str], None] = '5de239af28aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'password_has')
    op.drop_column('users', 'update')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_has', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
